version: "3"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3307:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    volumes:
      - data:/var/lib/mysql
  api:
    build: api/
    command: /bin/sh -c "rm -f tmp/pids/server.pid &&
      bundle install &&
      bundle exec rails db:create db:migrate &&
      bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./api:/app
      - bundle:/usr/local/bundle
    depends_on:
      - db
    ports:
      - 3000:3000
  front:
    build: front/
    command: /bin/sh -c "yarn install && yarn nuxt dev"
    volumes:
      - ./front:/app
      - node_modules:/app/node_modules
    ports:
      - 8081:8081
    environment:
      HOST: 0.0.0.0
      PORT: 8081
volumes:
  data:
  bundle:
  node_modules:
